services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: filipp
      POSTGRES_PASSWORD: filipp
      POSTGRES_DB: strapi
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data